version: '3'

services:

  # nodejs
  nodejs:
    image: ${NODE_IMAGE_NAME}:${NODE_IMAGE_VERSION}
    volumes:
      -  node-vol:/app
    ports:
      - '9000:9000'
    networks:
      - nodenetwork

networks:
  nodenetwork:

volumes:
  node-vol:
    driver: local
    driver_opts:
      type: none
      device: /app
      o: bind
